# Site settings
title: truth's develop blog
description: A blog about truth's develop study
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: truthone Developer
user_description: 한진실짱짱맨
user_title: web FE / web BE
email: truth.applicant@gmail.com
# twitter_username: 
github_username: github.com/truthone
# gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
